export type Point={x:number;y:number};
export type NodePoint=Point & {title?:string};
export const NODE_SIZE:Readonly<{width:number;height:number}>;
export const NODE_ANCHOR:Readonly<Point>;
export const NODE_GAP:Readonly<{x:number;y:number}>;
export const PREVIEW_SIZE:Readonly<{width:number;height:number}>;
export const READING_ZOOM:number;
export const MIN_CANVAS_ZOOM:number;
export const TITLE_LAYOUT:Readonly<{glyphWidth:number;minWidth:number;padding:number}>;
export function fullTitleWidth(title?:string):number;
export function nodeHalfWidth(title?:string):number;
export function nodeDisplayGeometry(zoom:number):{scale:number;factor:number;fontSize:number;lineHeight:number;titleTop:number;selectedTitleTop:number};
export function nodeVisualBounds(point:NodePoint,transform:{zoom:number;panX:number;panY:number}):{left:number;right:number;top:number;bottom:number};
export function nodeLayoutBounds(point:NodePoint):{left:number;right:number;top:number;bottom:number};
export function nodesOverlap(a:NodePoint,b:NodePoint):boolean;
export function freeNodePosition(preferred:NodePoint,occupied:NodePoint[]):Point;
export function directNeighborhood(id:string|null,connections:{fromId:string;toId:string}[],visibleIds:string[]):Set<string>;
export function arrangeRelationships<T extends NodePoint & {id:string;tags?:string[]}>(ideas:T[],connections:{fromId:string;toId:string}[],viewport?:{width:number;height:number}):T[];
export function aggregationBasis<T extends {fromId:string;toId:string}>(ideas:{id:string;tags?:string[]}[],connections:T[]):{nodeCount:number;connections:T[];tags:{tag:string;count:number;members:string[]}[];untaggedCount:number};
export function previewPosition(point:Point,transform:{panX:number;panY:number;zoom:number},viewport:{width:number;height:number},detailOpen?:boolean):{left:number;top:number;width:number;height:number};
export function sharedTagPeers(id:string|null,ideas:{id:string;tags?:string[]}[],connections:{fromId:string;toId:string}[],tag?:string):{fromId:string;toId:string;tags:string[]}[];
