import { readFile, writeFile, readdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import { projectRoot } from '../server/config.mjs';

const lock=JSON.parse(await readFile(resolve(projectRoot,'package-lock.json'),'utf8'));
const packages=[],notices=[];
for(const [location,entry] of Object.entries(lock.packages)) {
  if(!location)continue;
  packages.push({package:location,version:entry.version,license:entry.license || 'UNDECLARED',development:!!entry.dev,optional:!!entry.optional});
  try {
    const directory=resolve(projectRoot,location),files=await readdir(directory);
    const names=files.filter(name=>/^(licen[sc]e|copying|notice)(\.|$)/i.test(name));
    for(const name of names.sort()) {
      try {
        // 统一声明的换行和行尾空白，保留许可证条款；只修改生成源，不改依赖原件。
        const content=(await readFile(resolve(directory,name),'utf8')).replace(/\r\n?/g,'\n').replace(/[ \t]+$/gm,'');
        notices.push(`${location}@${entry.version} / ${name}\n${content}`);
      }
      catch(error){if(error.code!=='EISDIR')throw error;}
    }
  }catch(error){if(error.code!=='ENOENT')throw error;}
}
await writeFile(resolve(projectRoot,'doc/dependency-licenses.json'),JSON.stringify({source:'package-lock.json',packages},null,2)+'\n');
await writeFile(resolve(projectRoot,'vendor/THIRD-PARTY-NOTICES.txt'),'Generated by npm run licenses from installed packages. Regenerate after changing the lock file.\n\n'+notices.join('\n\n'+'='.repeat(72)+'\n\n')+'\n');
const missing=packages.filter(entry=>entry.license==='UNDECLARED');
console.log(JSON.stringify({lockedPackages:packages.length,noticeFiles:notices.length,licenseDeclarations:[...new Set(packages.map(entry=>entry.license))].sort(),missing}));
if(missing.length)process.exitCode=1;
